Repository OpenSTEF/openstef, pull requests merged in 2021-12, with the labels that each got.

#262 Fix bug for single dict in teams monitoring
  openstef/monitoring/teams.py
  setup.py
Labels: fix

#263 Update to OpenSTEF instead of alliander-opensource
  .github/workflows/docs-publish.yaml
  COMMITTERS.md
  openstef/pipeline/create_basecase_forecast.py
  setup.py
Labels: fix

#267 Bugfix ktps 1857 loading models
  openstef/model/serializer.py
  test/unit/model/serializer/test_serializer.py
  test/unit/pipeline/test_pipeline_create_forecast.py
  test/unit/tasks/test_create_forecast.py
Labels: fix

#270 Bugfix train quantile models
  openstef/pipeline/optimize_hyperparameters.py
  openstef/pipeline/train_model.py
  test/unit/pipeline/test_optimize_hyperparameters.py
  test/unit/pipeline/test_pipeline_train_model.py
Labels: fix

#266 Added the unit indication in the AbstractFeatureApplicator docstring
  openstef/feature_engineering/feature_applicator.py
Labels: chore

#264 Replaced hardcoded horizon by the time resolution
  openstef/pipeline/create_forecast.py
Labels: fix

#273 Feature ktps 1832 dashboard doc
  README.md
Labels: feature

#275 Update checkout reference version
  .github/workflows/black-format-code.yml
  .github/workflows/docs-check.yaml
  .github/workflows/docs-publish.yaml
Labels: chore

#277 Integration test for the general pipeline
  .github/workflows/python-build.yaml
  test/integration/__init__.py
  test/integration/test_integration.py
Labels: feature
