Repository OpenSTEF/openstef, pull requests merged in 2021-11, with the labels that each got.

#213 Bugfix ktps 1758 optimize hyperparams inf nan
  openstf/pipeline/optimize_hyperparameters.py
  openstf/tasks/utils/predictionjobloop.py
  test/unit/tasks/utils/test_prediction_job_loop.py
Labels: fix

#216 hotfix wrong variable reference
  openstf/pipeline/optimize_hyperparameters.py
Labels: fix

#215 update reviewers
  .github/dependabot.yml
Labels: chore

#194 Added an abstract feature_names property in OpenSFTRegressorInterface
  openstf/model/objective.py
  openstf/model/regressors/lgbm.py
  openstf/model/regressors/regressor.py
  openstf/model/regressors/regressor_interface.py
  openstf/model/regressors/xgb.py
  openstf/model/regressors/xgb_quantile.py
  openstf/pipeline/create_forecast.py
  openstf/pipeline/train_model.py
  test/trained_models/307/20211013125259/model.joblib
  test/trained_models/307/20211013125259/model.joblib.license
  test/unit/model/regressors/test_xgb_quantile.py
  test/unit/pipeline/test_train_model.py
Labels: fix

#210 Add feature to make dynamic forecasting start and end time based on forecast data instead of horizon
  .gitignore
  openstf/pipeline/create_basecase_forecast.py
  openstf/pipeline/create_forecast.py
  openstf/pipeline/utils.py
  openstf/tasks/create_forecast.py
  openstf/tasks/utils/predictionjobloop.py
  openstf/validation/validation.py
  test/unit/pipeline/test_create_forecast.py
  test/unit/tasks/test_create_forecast.py
Labels: feature

#218 Change back to old filepath for trained models to fix unit test
  test/unit/tasks/test_create_forecast.py
Labels: fix

#221 Remove modelage check from tasks\train_model.py
  openstf/tasks/train_model.py
  test/unit/tasks/test_train_model.py
Labels: fix

#223 Bugfix ktps 1778 model age incorrect
  setup.py
Labels: fix

#222 Feature ktps 1555 model specific parameters in mlflow
  openstf/dataclasses/model_specifications.py
  openstf/model/confidence_interval_applicator.py
  openstf/model/serializer.py
  openstf/monitoring/teams.py
  openstf/pipeline/create_basecase_forecast.py
  openstf/pipeline/create_component_forecast.py
  openstf/pipeline/create_forecast.py
  openstf/pipeline/optimize_hyperparameters.py
  openstf/pipeline/train_create_forecast_backtest.py
  openstf/pipeline/train_model.py
  openstf/postprocessing/postprocessing.py
  openstf/tasks/create_basecase_forecast.py
  openstf/tasks/create_components_forecast.py
  openstf/tasks/create_forecast.py
  openstf/tasks/optimize_hyperparameters.py
  openstf/tasks/run_tracy.py
  openstf/tasks/split_forecast.py
  openstf/tasks/train_model.py
  requirements.txt
  test/unit/data/prediction_jobs.json
  test/unit/model/serializer/test_serializer.py
  test/unit/model/test_objective.py
  test/unit/pipeline/test_create_basecase.py
  test/unit/pipeline/test_create_component_forecast.py
  test/unit/pipeline/test_create_forecast.py
  test/unit/pipeline/test_optimize_hyperparameters.py
  test/unit/pipeline/test_train_model.py
  test/unit/pipeline/test_train_predict_backtest.py
  test/unit/tasks/test_calculate_kpi.py
  test/unit/tasks/test_create_forecast.py
  test/unit/tasks/test_train_model.py
  test/utils/data.py
Labels: feature

#226 remove wrong/unused imports and add init to dataclasses folder
  openstf/data_classes/__init__.py
  openstf/data_classes/model_specifications.py
  openstf/model/serializer.py
  openstf/pipeline/create_forecast.py
  openstf/pipeline/optimize_hyperparameters.py
  openstf/pipeline/train_create_forecast_backtest.py
  openstf/pipeline/train_model.py
  openstf/pipeline/utils.py
  openstf/tasks/optimize_hyperparameters.py
  openstf/tasks/train_model.py
  setup.py
  test/unit/data_classes/__init__.py
  test/unit/data_classes/test_model_specifications.py
  test/unit/model/serializer/test_serializer.py
  test/utils/data.py
Labels: feature

#228 Bugfix ktps 1805 remove old models from disk
  openstf/model/serializer.py
  test/unit/model/serializer/test_serializer.py
Labels: fix

#234 Chore move healthdocs to org
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md.license
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/documentation.md.license
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md.license
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md.license
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  SUPPORT.md
Labels: chore

#235 Backtest for the entire input range (using cross validation with nfolds)
  openstf/model_selection/model_selection.py
  openstf/pipeline/train_create_forecast_backtest.py
  openstf/pipeline/train_model.py
  test/unit/data/prediction_jobs.json
  test/unit/pipeline/test_train_predict_backtest.py
Labels: feature

#236 remove capacity prognoses
  openstf/feature_engineering/capacity_prognoses_features.py
  openstf/model/capacity/__init__.py
  openstf/model/capacity/model.py
  openstf/model/capacity/predict.py
  openstf/model/capacity/train.py
  openstf/model/capacity/utils.py
  openstf/tasks/create_capacity_forecast.py
  openstf/tasks/train_capacity_model.py
  test/unit/feature_engineering/test_capacity_prognoses_features.py
  test/unit/model/capacity/__init__.py
  test/unit/model/capacity/test_capacity_predict.py
  test/unit/model/capacity/test_capacity_train.py
  test/unit/model/capacity/test_capacity_utils.py
Labels: fix

#238 Bugfix ktps 1823 fix validation robot
  openstf/preprocessing/preprocessing.py
  openstf/validation/validation.py
  test/unit/preprocessing/test_preprocessing.py
  test/unit/validation/test_validation_find_nonzero_flatliners.py
  test/unit/validation/test_validation_find_zero_flatliners.py
Labels: fix

#239 Fixed typo in defining quantile columns
  openstf/pipeline/train_create_forecast_backtest.py
Labels: fix

#243 update reference implementation link
  README.md
Labels: chore

#247 Improve find models function in mlflow serializer
  openstf/model/serializer.py
  setup.py
  test/unit/model/serializer/test_serializer.py
Labels: fix

#251 Update mlflow 1.21.0
  requirements.txt
Labels: chore

#252 add functionality to store reports to disk
  openstf/metrics/reporter.py
  openstf/model/serializer.py
  test/unit/model/serializer/test_serializer.py
  test/unit/pipeline/test_train_model.py
Labels: feature

#254 Improve hyperarameter optimization
  openstf/model/objective.py
  openstf/pipeline/optimize_hyperparameters.py
  openstf/tasks/optimize_hyperparameters.py
Labels: fix

#219 Feature #184 implement linear regression model
  openstf/enums.py
  openstf/model/metamodels/__init__.py
  openstf/model/metamodels/missing_values_handler.py
  openstf/model/model_creator.py
  openstf/model/objective.py
  openstf/model/objective_creator.py
  openstf/model/regressors/linear.py
  test/unit/model/regressors/test_linear.py
  test/unit/model/test_objective.py
  test/unit/pipeline/test_train_model.py
Labels: feature

#257 Fix dependencies
  requirements.txt
  setup.py
Labels: fix
