Repository OpenSTEF/openstef, pull requests merged in 2021-08, with the labels that each got.

#137 add auto labler action
  .github/pr-labler.yml
  .github/release-drafter.yml
  .github/workflows/pr-labler.yaml
Labels: feature

#138 Docs add action docstrings
  .github/pr-labler.yml
  .github/release-drafter.yml
  .github/workflows/pr-labler.yaml
  .github/workflows/release-drafter.yaml
Labels: chore

#142 remove obs label
  .github/pr-labeler.yml
Labels: chore

#144 Update release-drafter.yml
  .github/release-drafter.yml
Labels: chore

#146 Update create_basecase_forecast.py
  openstf/tasks/create_basecase_forecast.py
Labels: fix

#143 change model kwargs to single line
  openstf/model/model_creator.py
Labels: chore

#149 raise clear exception on unimplemented model
  openstf/model/objective_creator.py
  test/unit/model/test_objective_creator.py
Labels: fix

#150 if multiple exceptions are raised in a task, present an overview of pids per exception in teams message
  openstf/tasks/utils/predictionjobloop.py
  openstf/tasks/utils/taskcontext.py
  test/unit/tasks/utils/test_task_context.py
Labels: feature

#151 Feature better exceptions train model pipeline
  .github/workflows/docs-check.yaml
  .github/workflows/docs-publish.yaml
  openstf/exceptions.py
  openstf/model/confidence_interval_applicator.py
  openstf/model/serializer.py
  openstf/pipeline/train_model.py
  openstf/tasks/calculate_kpi.py
  openstf/tasks/create_forecast.py
  pyproject.toml
  setup.cfg
  setup.py
  test/unit/pipeline/test_train_model.py
  test/unit/tasks/test_calculate_kpi.py
Labels: feature
