Repository OpenSTEF/openstef, pull requests merged in 2022-01, with the labels that each got.

#281 fixed unit tests due to bevrijdingsdag issue
  test/unit/data/input_data_multi_horizon_features.csv
  test/unit/data/input_data_with_holiday_features.csv
  test/unit/feature_engineering/test_apply_features.py
  test/unit/feature_engineering/test_feature_free_days.py
Labels: fix

#279 make location dynamic
  openstef/model/serializer.py
Labels: fix

#284 Feature/1749 setup mlflow for distributed mlflow tracking server
  .gitignore
  openstef/model/serializer.py
  openstef/pipeline/create_forecast.py
  requirements.txt
  setup.py
Labels: feature

#292 Update maintainers
  PROJECT_GOVERNANCE.md
Labels: chore

#291 Bugfix ktps 1929 train val split
  openstef/model/objective.py
  openstef/model_selection/model_selection.py
  openstef/pipeline/train_model.py
  test/unit/model/test_model_selection.py
  test/unit/pipeline/test_pipeline_train_model.py
  test/unit/pipeline/test_train.py
Labels: fix

#297 Fix/calculate kpi
  openstef/tasks/calculate_kpi.py
Labels: fix
