Repository OpenSTEF/openstef, pull requests merged in 2022-03, with the labels that each got.

#309 test can_predict_quantiles attribute
  test/unit/model/test_model_creator.py
Labels: chore

#312 Update requirements and fix unit tests
  openstef/preprocessing/preprocessing.py
  requirements.txt
  setup.py
  test/unit/feature_engineering/test_weather.py
  test/unit/validation/test_validation_find_zero_flatliners.py
Labels: chore

#305 Add the property indicating if a model can predict quantiles
  openstef/model/basecase.py
  openstef/model/confidence_interval_applicator.py
  openstef/model/regressors/lgbm.py
  openstef/model/regressors/linear.py
  openstef/model/regressors/proloaf.py
  openstef/model/regressors/regressor_interface.py
  openstef/model/regressors/xgb.py
  openstef/model/regressors/xgb_quantile.py
  test/unit/model/test_confidence_interval_applicator.py
  test/unit/model/test_custom_models.py
  test/unit/model/test_model_creator.py
  test/unit/pipeline/test_pipeline_train_model.py
Labels: feature

#323 Bugfix train full quantile model after hyperparameter optimization
  openstef/pipeline/optimize_hyperparameters.py
  setup.py
Labels: fix

#322 Same end time for all PJs of a task
  openstef/tasks/train_model.py
Labels: feature

#311 Update list type and clean up feature_adder
  openstef/feature_engineering/feature_adder.py
Labels: chore

#324 fixed bug
  openstef/tasks/train_model.py
  setup.py
Labels: fix

#328 Fix quantile xgb ojective function
  .github/workflows/docs-check.yaml
  openstef/metrics/metrics.py
Labels: fix
