Repository OpenSTEF/openstef, pull requests merged in 2022-04, with the labels that each got.

#319 WIP: Added possibility to save the forecasts on the train datasets
  openstef/data_classes/prediction_job.py
  openstef/pipeline/train_model.py
  openstef/tasks/create_solar_forecast.py
  openstef/tasks/train_model.py
  test/unit/model/test_model_selection.py
  test/unit/pipeline/test_pipeline_train_model.py
Labels: feature

#320 WIP: Possibility to specify the horizons used for training
  openstef/data_classes/prediction_job.py
  openstef/feature_engineering/feature_applicator.py
  openstef/pipeline/train_model.py
  test/unit/feature_engineering/test_feature_applicator.py
  test/unit/pipeline/test_pipeline_train_model.py
Labels: feature

#259 Feature #244 grouped regressor metamodel
  .github/workflows/black-format-code.yml
  .github/workflows/python-build.yaml
  openstef/feature_engineering/feature_adder.py
  openstef/feature_engineering/historic_features.py
  openstef/feature_engineering/lag_features.py
  openstef/feature_engineering/weather_features.py
  openstef/model/basecase.py
  openstef/model/metamodels/grouped_regressor.py
  openstef/model/model_creator.py
  openstef/model/objective_creator.py
  openstef/model/regressors/custom_regressor.py
  openstef/model/serializer.py
  openstef/model_selection/model_selection.py
  openstef/pipeline/create_component_forecast.py
  openstef/pipeline/optimize_hyperparameters.py
  openstef/pipeline/train_model.py
  openstef/postprocessing/postprocessing.py
  openstef/tasks/calculate_kpi.py
  openstef/tasks/create_basecase_forecast.py
  openstef/tasks/create_components_forecast.py
  openstef/tasks/create_forecast.py
  openstef/tasks/create_solar_forecast.py
  openstef/tasks/create_wind_forecast.py
  openstef/tasks/optimize_hyperparameters.py
  openstef/tasks/run_tracy.py
  openstef/tasks/split_forecast.py
  openstef/tasks/train_model.py
  openstef/tasks/utils/predictionjobloop.py
  openstef/validation/validation.py
  sonar-project.properties
  test/unit/model/metamodels/test_grouped_regressor.py
  test/unit/model/regressors/test_linear.py
  test/unit/model/regressors/test_proloaf.py
  test/unit/model/serializer/test_serializer.py
  test/unit/monitoring/test_teams.py
Labels: feature

#338 Feature/ktps 2029 improved exception message
  openstef/pipeline/create_basecase_forecast.py
  test/unit/pipeline/test_create_basecase.py
Labels: feature

#337 Bugfix/change skillscore signature
  test/unit/data/calculate_kpi_kpi.json
  test/unit/tasks/test_calculate_kpi.py
  test/unit/utils/data.py
Labels: fix

#346 fix future warnings
  openstef/feature_engineering/feature_applicator.py
  openstef/model/standard_deviation_generator.py
  openstef/model_selection/model_selection.py
Labels: chore

#349 Skip writing none figure
  openstef/metrics/reporter.py
  test/unit/metrics/test_reporter.py
Labels: chore

#341 Make the train pipeline return the datasets with forecasts
  openstef/model_selection/model_selection.py
  openstef/pipeline/optimize_hyperparameters.py
  openstef/pipeline/train_model.py
  openstef/tasks/train_model.py
  test/unit/pipeline/test_pipeline_train_model.py
  test/unit/tasks/test_train_model.py
Labels: fix

#351 Update prediction job class to have optional train components for cre…
  openstef/data_classes/prediction_job.py
  setup.py
Labels: chore

#352 Add the serialization of feature_modules
  openstef/model/serializer.py
  test/unit/model/test_serializer.py
Labels: fix

#353 Fix prediction job for wind and solar forecasts, and run isort and black
  openstef/data_classes/prediction_job.py
  openstef/pipeline/train_model.py
  openstef/tasks/create_solar_forecast.py
  setup.py
  test/unit/data_classes/test_prediction_job.py
  test/unit/tasks/test_train_model.py
Labels: chore
