Repository OpenSTEF/openstef, pull requests merged in 2022-05, with the labels that each got.

#357 fix-serialization-issue
  openstef/model/objective.py
  setup.py
Labels: fix

#358 fix-make-fold-randomization-backtest-configurable
  openstef/model_selection/model_selection.py
Labels: fix

#355 Switch to automatic version bumping and release, fix black with signoff and fix deprecated append to concat
  .github/bump_version.py
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/black-format-code.yml
  .github/workflows/docs-check.yaml
  .github/workflows/docs-publish.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/release.yaml
  openstef/feature_engineering/feature_applicator.py
  openstef/model/basecase.py
  openstef/pipeline/train_model.py
  openstef/tasks/create_solar_forecast.py
  openstef/validation/validation.py
  test/unit/validation/test_validation_find_zero_flatliners.py
Labels: chore, feature

#359 Test new release by cleaning up unit test
  test/unit/validation/test_validation_find_nonzero_flatliners.py
Labels: chore

#360 Update release trigger
  .github/workflows/release.yaml
  openstef/model/serializer.py
  test/unit/validation/test_validation_check_data_for_each_trafo.py
Labels: chore

#361 Add new access token for release and cleanup test
  .github/workflows/release.yaml
  test/unit/validation/test_validation_calc_completeness.py
Labels: chore

#362 Clean up logging to fix logging indexes in elastic
  openstef/model/serializer.py
Labels: chore

#363 Upload new pypi on every release
  .github/workflows/python-upload-package.yaml
  test/unit/tasks/test_calculate_kpi.py
Labels: chore

#364 Use PAT instead of standard github token to trigger release
  .github/workflows/release.yaml
Labels: chore

#366 Fix authentication for release
  .github/workflows/release.yaml
Labels: chore

#370 Update plotly
  requirements.txt
Labels: chore

#374 Chore/test auto release
  .github/workflows/release.yaml
  requirements.txt
Labels: chore
