Repository OpenSTEF/openstef, pull requests merged in 2022-02, with the labels that each got.

#303 Update create_basecase_forecast.py
  openstef/pipeline/create_basecase_forecast.py
  openstef/validation/validation.py
  test/unit/pipeline/test_create_basecase.py
  test/unit/validation/test_validation.py
Labels: fix

#304 Chore/update versions
  openstef/data_classes/prediction_job.py
  openstef/exceptions.py
  openstef/feature_engineering/apply_features.py
  openstef/feature_engineering/feature_applicator.py
  openstef/feature_engineering/historic_features.py
  openstef/model/confidence_interval_applicator.py
  openstef/model/serializer.py
  openstef/monitoring/teams.py
  openstef/pipeline/create_basecase_forecast.py
  openstef/pipeline/create_component_forecast.py
  openstef/pipeline/create_forecast.py
  openstef/pipeline/optimize_hyperparameters.py
  openstef/pipeline/train_create_forecast_backtest.py
  openstef/pipeline/train_model.py
  openstef/postprocessing/postprocessing.py
  openstef/tasks/calculate_kpi.py
  openstef/tasks/create_basecase_forecast.py
  openstef/tasks/create_components_forecast.py
  openstef/tasks/create_forecast.py
  openstef/tasks/create_solar_forecast.py
  openstef/tasks/create_wind_forecast.py
  openstef/tasks/optimize_hyperparameters.py
  openstef/tasks/run_tracy.py
  openstef/tasks/split_forecast.py
  openstef/tasks/train_model.py
  openstef/tasks/utils/taskcontext.py
  requirements.txt
  result.json
  setup.py
  test/unit/data/calculate_kpi_kpi.json
  test/unit/model/serializer/test_serializer.py
  test/unit/monitoring/test_teams.py
  test/unit/pipeline/test_pipeline_train_model.py
  test/unit/tasks/test_calculate_kpi.py
  test/unit/tasks/test_create_forecast.py
  test/unit/tasks/utils/test_task_context.py
  test/unit/utils/base.py
  test/unit/utils/data.py
Labels: chore

#246 Feature #187 add feature adder
  openstef/data_classes/model_specifications.py
  openstef/feature_engineering/feature_adder.py
  openstef/feature_engineering/feature_applicator.py
  openstef/pipeline/create_forecast.py
  openstef/pipeline/train_model.py
  test/integration/test_integration.py
  test/unit/feature_engineering/test_feature_adder.py
  test/unit/pipeline/test_pipeline_create_forecast.py
  test/unit/pipeline/test_pipeline_train_model.py
Labels: feature

#306 Remove sonar quality gate
  README.md
Labels: chore
