Repository OpenSTEF/openstef, pull requests merged in 2022-07, with the labels that each got.

#376 Improve performance of replace repeated values with nan
  openstef/data_classes/prediction_job.py
  openstef/data_classes/split_function.py
  openstef/model_selection/model_selection.py
  openstef/pipeline/optimize_hyperparameters.py
  openstef/pipeline/train_create_forecast_backtest.py
  openstef/preprocessing/preprocessing.py
  test/unit/data_classes/test_split_function.py
  test/unit/pipeline/test_optimize_hyperparameters.py
  test/unit/pipeline/test_train.py
  test/unit/pipeline/test_train_predict_backtest.py
  test/unit/preprocessing/test_preprocessing.py
  test/unit/validation/test_validation.py
Labels: chore

#381 Fix typo in readme
  README.md
Labels: chore

#379 windspeed converted into windenergy
  openstef/postprocessing/postprocessing.py
  test/unit/postprocessing/test_postprocessing.py
Labels: feature

#383 improve optional proloaf dependency
  openstef/enums.py
  openstef/model/model_creator.py
  test/unit/model/test_model_creator.py
  test/unit/pipeline/test_pipeline_train_model.py
Labels: chore

#382 Bugfix ktps 2272 #380 reporter location
  openstef/feature_engineering/holiday_features.py
  openstef/metrics/reporter.py
  openstef/pipeline/optimize_hyperparameters.py
  openstef/pipeline/train_model.py
  test/component/test_component.py
  test/unit/pipeline/test_pipeline_train_model.py
Labels: fix

#386 Hotfix/ktps 2289 none pj solar features
  openstef/data_classes/prediction_job.py
  openstef/feature_engineering/apply_features.py
  openstef/feature_engineering/feature_applicator.py
  openstef/feature_engineering/historic_features.py
  openstef/feature_engineering/weather_features.py
  test/unit/data/input_data_multi_horizon_features.csv
  test/unit/data/input_data_with_features.csv
  test/unit/feature_engineering/test_apply_features.py
  test/unit/model/test_objective.py
Labels: fix

#384 update xgboost, pandas, optuna
  openstef/feature_engineering/apply_features.py
  openstef/model/model_creator.py
  openstef/model/regressors/regressor_interface.py
  openstef/model/serializer.py
  openstef/pipeline/train_model.py
  openstef/pipeline/utils.py
  requirements.txt
  test/unit/feature_engineering/test_apply_features.py
Labels: chore

#387 Bugfix ktps 2298 feature mismatch
  openstef/pipeline/create_forecast.py
  test/unit/pipeline/test_pipeline_create_forecast.py
  test/unit/pipeline/test_pipeline_train_model.py
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/artifacts/model/MLmodel
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/artifacts/model/conda.yaml
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/artifacts/model/model.pkl
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/artifacts/model/requirements.txt
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/meta.yaml
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/metrics/MAE
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/metrics/MSE
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/metrics/NSME
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/metrics/RMSE
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/metrics/R_MAE
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/metrics/bias
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/metrics/explained_variance
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/metrics/r2
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/tags/Previous_version_id
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/tags/feature_names
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/tags/mlflow.log-model.history
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/tags/mlflow.runName
  test/unit/trained_models/mlruns/0/d7719d5d316d4416a947e4f7ea7e73a8/tags/run_id
Labels: fix
