Repository OpenSTEF/openstef, pull requests merged in 2023-08, with the labels that each got.

#466 skip failing test
  test/unit/pipeline/test_create_component_forecast.py
Labels: fix

#471 add uncertainty estimation docs
  docs/_static/methodology_train_predict.pptx
  docs/_static/uncertainty_estimation.svg
  docs/_static/uncertainty_estimation.svg.license
  docs/methodology_train_predict.rst
Labels: chore

#472 remove incorrect report creation
  openstef/pipeline/optimize_hyperparameters.py
Labels: fix

#473 Speed up train_model task: extra model age check
  openstef/pipeline/train_model.py
  openstef/tasks/train_model.py
Labels: feature
