Repository OpenSTEF/openstef, pull requests merged in 2024-01, with the labels that each got.

#491 Update python-upload-package.yaml
  .github/workflows/python-upload-package.yaml
  openstef/feature_engineering/holiday_features.py
  test/unit/data/input_data_multi_horizon_features.csv
  test/unit/data/input_data_with_features.csv
  test/unit/data/input_data_with_holiday_features.csv
  test/unit/feature_engineering/test_apply_features.py
  test/unit/feature_engineering/test_feature_free_days.py
  test/unit/tasks/test_train_model.py
Labels: chore

#493 Forecast zeros as fallback for zero flatliners
  .github/workflows/black-format-code.yml
  openstef/pipeline/create_basecase_forecast.py
  openstef/tasks/create_forecast.py
  openstef/tasks/split_forecast.py
  openstef/validation/validation.py
  test/unit/feature_engineering/test_apply_features.py
  test/unit/tasks/test_create_forecast.py
Labels: feature

#483 By default only detect zero flatliners after a full day of the zero flatliner pattern
  openstef/data_classes/prediction_job.py
  test/unit/validation/test_validation.py
Labels: fix
