Repository OpenSTEF/openstef, pull requests merged in 2024-03, with the labels that each got.

#511 Updated requirements.txt to use more permissive contraints for structlog.
  requirements.txt
Labels: fix

#517 remove all proloaf references
  README.md
  openstef/data_classes/prediction_job.py
  openstef/enums.py
  openstef/feature_engineering/apply_features.py
  openstef/feature_engineering/feature_applicator.py
  openstef/feature_engineering/historic_features.py
  openstef/model/model_creator.py
  openstef/model/objective.py
  openstef/model/objective_creator.py
  openstef/model/regressors/proloaf.py
  openstef/pipeline/optimize_hyperparameters.py
  openstef/pipeline/train_create_forecast_backtest.py
  openstef/pipeline/train_model.py
  requirements.txt
  setup.py
  test/unit/feature_engineering/test_feature_applicator.py
  test/unit/model/regressors/test_proloaf.py
  test/unit/model/test_model_creator.py
  test/unit/model/test_objective.py
  test/unit/pipeline/test_pipeline_train_model.py
Labels: chore

#521 docs(KTP-673) Added missing documentation for possible raised exceptions.
  openstef/metrics/figure.py
  openstef/metrics/metrics.py
  openstef/model/confidence_interval_applicator.py
  openstef/model/regressors/xgb_quantile.py
  openstef/model/serializer.py
  openstef/model_selection/model_selection.py
  openstef/pipeline/create_basecase_forecast.py
  openstef/pipeline/create_forecast.py
  openstef/pipeline/optimize_hyperparameters.py
  openstef/pipeline/train_create_forecast_backtest.py
  openstef/pipeline/train_model.py
  openstef/pipeline/utils.py
  openstef/tasks/create_components_forecast.py
  openstef/tasks/train_model.py
  openstef/validation/validation.py
Labels: chore

#519 Improve readme
  README.md
Labels: chore

#523 Optional teams messages
  openstef/app_settings.py
  openstef/exceptions.py
  openstef/monitoring/teams.py
Labels: feature
