Repository OpenSTEF/openstef, pull requests merged in 2025-09, with the labels that each got.

#660 feature(#628): Updated package deps.
  packages/openstef-core/pyproject.toml
  packages/openstef-models/pyproject.toml
  pyproject.toml
  uv.lock
Labels: feature

#663 feature(#626): Air-related Features Transform
  packages/openstef-models/src/openstef_models/feature_engineering/weather_transforms/atmosphere_derived_features_transform.py
  packages/openstef-models/tests/unit/feature_engineering/weather_transforms/test_atmosphere_derived_features_transform.py
Labels: feature, OpenSTEF 4.0

#668 fix(STEF-2391): Improved feature clipping (to avoid extrapolation) by switching it from minmax to std clipping.
  openstef/model/metamodels/feature_clipper.py
  test/unit/model/metamodels/test_feature_clipper.py
  test/unit/model/regressors/test_gblinear_quantile.py
  test/unit/model/regressors/test_linear_quantile.py
Labels: fix

#675 add rIQD and relative pinball loss metrics
  packages/openstef-beam/src/openstef_beam/evaluation/metric_providers.py
  packages/openstef-beam/src/openstef_beam/metrics/__init__.py
  packages/openstef-beam/src/openstef_beam/metrics/metrics_deterministic.py
  packages/openstef-beam/tests/unit/evaluation/test_metric_provider.py
  packages/openstef-beam/tests/unit/metrics/test_metrics_deterministic.py
Labels: feature

#676 Add option to plot timeseries without interpolated lines where gaps in data
  packages/openstef-beam/src/openstef_beam/analysis/plots/forecast_time_series_plotter.py
  packages/openstef-beam/src/openstef_beam/analysis/visualizations/timeseries_visualization.py
  packages/openstef-beam/tests/unit/analysis/plots/test_forecast_time_series_plotter.py
  packages/openstef-beam/tests/unit/analysis/visualizations/test_timeseries_visualization.py
Labels: feature

#696 feature(#688): add FlatlinerForecaster
  packages/openstef-models/src/openstef_models/models/forecasting/flatliner_forecaster.py
  packages/openstef-models/src/openstef_models/models/forecasting/forecaster.py
  packages/openstef-models/tests/unit/models/forecasting/test_flatliner_forecaster.py
Labels: feature

#702 feature(#689): Add basecase forecaster
  packages/openstef-models/src/openstef_models/models/forecasting/base_case_forecaster.py
  packages/openstef-models/tests/unit/models/forecasting/test_base_case_forecaster.py
Labels: feature
